import React, { useEffect, useState } from 'react';
import { UserPlus, Shield, Trash2, X, ShieldAlert, RefreshCw } from 'lucide-react';
import { supabase } from '../lib/supabase';

const roles = ['Super Admin', 'Admin', 'Moderator'];

export default function UserManagement({ currentUser }) {
  const [users, setUsers] = useState([]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [form, setForm] = useState({ email: '', role: 'Moderator' });
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const loadUsers = async () => { setLoading(true); const { data, error: loadError } = await supabase.rpc('list_staff'); if (loadError) setError(loadError.message); else setUsers(data || []); setLoading(false); };
  useEffect(() => { loadUsers(); }, []);
  const saveUser = async (event) => { event.preventDefault(); setSaving(true); setError(''); const { error: saveError } = await supabase.rpc('grant_staff_access', { target_email: form.email.trim(), target_role: form.role }); setSaving(false); if (saveError) { setError(saveError.message); return; } setIsModalOpen(false); setForm({ email: '', role: 'Moderator' }); loadUsers(); };
  const removeUser = async (user) => { if (user.user_id === currentUser.id || !window.confirm(`Remove ${user.email}'s access to the admin panel?`)) return; const { error: removeError } = await supabase.rpc('revoke_staff_access', { target_user_id: user.user_id }); if (removeError) { setError(removeError.message); return; } loadUsers(); };
  const color = (role) => ({ 'Super Admin': 'bg-blue-100 text-blue-800 border-blue-200', Admin: 'bg-emerald-100 text-emerald-800 border-emerald-200', Moderator: 'bg-amber-100 text-amber-800 border-amber-200' }[role] || 'bg-gray-100 text-gray-800 border-gray-200');
  return <div className="space-y-6">
    <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center bg-white p-6 rounded-2xl shadow-sm border border-gray-100 gap-4"><div><h2 className="text-xl font-bold text-gray-900">Staff Access Control 👥</h2><p className="text-sm text-gray-500 mt-1">Grant, change, or revoke admin-panel access.</p></div><button onClick={() => { setError(''); setIsModalOpen(true); }} className="bg-blue-600 hover:bg-blue-700 text-white font-semibold px-4 py-2.5 rounded-xl shadow-sm flex items-center gap-2"><UserPlus className="w-5 h-5" /> Add or update staff</button></div>
    {error && <div className="p-3 bg-red-50 text-red-700 rounded-xl text-sm font-medium flex gap-2 border border-red-150"><ShieldAlert className="w-5 h-5 shrink-0" />{error}</div>}
    <div className="bg-blue-50 border border-blue-100 text-blue-800 rounded-2xl p-4 text-sm"><b>Before adding:</b> the person must first have a Supabase Authentication account with this email. Moderator manages orders; Admin manages products and orders; Super Admin also manages staff access.</div>
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden"><div className="p-4 border-b border-gray-100 flex justify-between items-center"><span className="font-semibold text-gray-700">{users.length} staff account{users.length === 1 ? '' : 's'}</span><button onClick={loadUsers} className="p-2 text-gray-500 hover:bg-gray-50 rounded-lg" title="Refresh"><RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} /></button></div><div className="overflow-x-auto"><table className="w-full text-left border-collapse"><thead><tr className="bg-gray-50 text-[11px] uppercase tracking-wider text-gray-400 border-b border-gray-100"><th className="px-6 py-4">User</th><th className="px-6 py-4">Email</th><th className="px-6 py-4">Role</th><th className="px-6 py-4 text-right">Action</th></tr></thead><tbody className="divide-y divide-gray-50 text-sm">{users.map(user => <tr key={user.user_id}><td className="px-6 py-4 font-semibold text-gray-900">{user.name}{user.user_id === currentUser.id && <span className="ml-2 text-[10px] bg-blue-100 text-blue-800 font-bold px-1.5 py-0.5 rounded">YOU</span>}</td><td className="px-6 py-4 text-gray-600">{user.email}</td><td className="px-6 py-4"><span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold border ${color(user.role)}`}><Shield className="w-3.5 h-3.5" />{user.role}</span></td><td className="px-6 py-4 text-right"><button disabled={user.user_id === currentUser.id} onClick={() => removeUser(user)} className="p-2 text-red-600 hover:bg-red-50 rounded-xl disabled:text-gray-300" title="Remove access"><Trash2 className="w-4 h-4" /></button></td></tr>)}</tbody></table></div></div>
    {isModalOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="bg-white rounded-2xl max-w-md w-full shadow-2xl overflow-hidden"><div className="px-6 py-4 bg-gray-50 border-b flex justify-between"><h3 className="text-lg font-bold">Add or update staff access</h3><button onClick={() => setIsModalOpen(false)}><X className="w-5 h-5" /></button></div><form onSubmit={saveUser} className="p-6 space-y-4"><div><label className="text-xs font-bold text-gray-500 uppercase">Registered account email</label><input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="staff@example.com" className="w-full mt-1 px-4 py-2.5 border border-gray-200 rounded-xl outline-none focus:border-blue-500" /></div><div><label className="text-xs font-bold text-gray-500 uppercase">Access role</label><select value={form.role} onChange={e => setForm({ ...form, role: e.target.value })} className="w-full mt-1 px-4 py-2.5 border border-gray-200 rounded-xl bg-white">{roles.map(role => <option key={role}>{role}</option>)}</select></div><div className="flex justify-end gap-3 pt-3"><button type="button" onClick={() => setIsModalOpen(false)} className="px-4 py-2 border border-gray-200 rounded-xl">Cancel</button><button disabled={saving} className="px-4 py-2 bg-blue-600 text-white rounded-xl font-semibold disabled:opacity-60">{saving ? 'Saving...' : 'Save access'}</button></div></form></div></div>}
  </div>;
}
